name: "AI Code Review Action"
description: "Perform code reviews and comment on diffs using OpenAI API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT."
    required: true
  OPENAI_API_MODEL:
    description: "OpenAI API model to use for generating reviews."
    required: false
    default: "o3-mini-2025-01-31"
  EXCLUDE_PATTERNS:
    description: "Comma-separated list of glob patterns to exclude files from the diff analysis."
    required: false
    default: ""
  CUSTOM_PROMPT:
    description: "Custom extra prompt for the AI code review."
    required: false
    default: ""
  FALLBACK_TO_GENERAL_COMMENT:
    description: "When set to true, will post as a general PR comment if inline commenting fails."
    required: false
    default: "true"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
outputs:
  commentsCount:
    description: "The number of comments made by the AI."
  totalCost:
    description: "The total estimated cost of the API usage."
